server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false

          routes:
            - id: user_service_base
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**


            - id: event_service_route
              uri: lb://EVENT-SERVICE
              predicates:
                - Path=/api/v1/events/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka